name: CIbstack dispatch
on: 
  workflow_dispatch:
    inputs:
      platform:
        description: 'Select where to run'
        required: true
        default: 'github'
        type: choice
        options:
        - github
        - bstack
      artifacts:
        description: 'reporting'
        required: false
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          run: npm run wdio
        - uses: actions/upload-artifact@v3
          if: failure()
          with:
            name: allureReport
            path: ./reports/allure/allure-report
